name: Github Actions
on: [push]

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/*/package*.json') }}
          restore-keys: npm-
      - run: npm ci
      - run: npm run build
      - run: npm run storybook:build
      - uses: JS-DevTools/npm-publish@v1
        if: contains(github.ref, 'master')
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public

